<br />
<h3 class="page-header"> &nbsp; &nbsp; <i class="icon-cogs"></i> &nbsp; Manutenção de Produtos</h3>
<!--===DashBoard===-->
<div class="switch-board gray">
    <div class="row-fluid">
        <div class="span2">
            <div class="board-widgets  btn-inverse small-widget span12">
                <a href="<?= $this->url('admin-index',array('controller' => 'produto')); ?>">
                    <span class="widget-icon icon-tag"></span>
                    <span class="widget-label">Produtos</span>
                </a>
            </div>
            
        </div>
        <div class="span4">
            <ul class="clearfix switch-item">
                <li>
                    <a href="<?= $this->url('new', array('controller' => 'produto')); ?>" class="green">
                        <i class="icon-file"></i>
                        <span>Novo</span>
                    </a>
                </li>
                <li>
                    <a href="<?= $this->url('edit', array('controller' => 'produto')); ?>" class="blue">
                        <i class="icon-pencil"></i>
                        <span>Editar</span>
                    </a>
                </li>
                <li>
                    <a href="<?= $this->url('delete', array('controller' => 'produto')); ?>" class="brown">
                        <i class="icon-remove"></i>
                        <span>Excluir</span>
                    </a>
                </li>
            </ul>
        </div>
        
        <div class="span2">
            <div class="board-widgets btn-inverse small-widget span12">
                <a href="<?= $this->url('admin-index',array('controller' => 'produto')); ?>">
                    <span class="widget-icon icon-tags"></span>
                    <span class="widget-label">Itens</span>
                </a>
            </div>
            
        </div>
        <div class="span4">
            <ul class="clearfix switch-item">
                <li>
                    <a href="<?= $this->url('new', array('controller' => 'itens')); ?>" class="green">
                        <i class="icon-file"></i>
                        <span>Novo</span>
                    </a>
                </li>
                <li>
                    <a href="<?= $this->url('edit', array('controller' => 'itens')); ?>" class="blue">
                        <i class="icon-pencil"></i>
                        <span>Editar</span>
                    </a>
                </li>
                <li>
                    <a href="<?= $this->url('delete', array('controller' => 'itens')); ?>" class="brown">
                        <i class="icon-remove"></i>
                        <span>Excluir</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    
</div>
<!--===DashBoard===-->
