<br />
<h3 class="page-header"> &nbsp; &nbsp; <i class="icon-tags"></i> &nbsp; Pedidos</h3>
<div class="well">
    <table class="table table-bordered table-hover table-striped">
        <tr>
            <td style="text-align: center;"><b>Senha</b></td>
            <td style="text-align: center;"><b>Cliente</b></td>
            <td style="text-align: center;"><b>Qtd. Produtos</b></td>
            <td style="text-align: center;"><b>Valor Total</b></td>
            <td style="text-align: center;"><b>Status</b></td>
            <td style="text-align: center;"><b>Ver</b></td>
        </tr>
        <?php if(count($this->pedidos) == 0): $modal = false;?>
            <tr>
                <td colspan="6" style="text-align: center;"><h4>Não possui pedidos concluidos!</h4></td>
            </tr>
        <?php else: $modal = true ?>
        <?php endif; ?>
        
        <?php if($modal): ?>
            <?php foreach($this->pedidos as $pedido): ?>
            <tr id="linha<?= $pedido->getId(); ?>">
                <?php 
                    $total = 0;
                    foreach($pedido->getProdutoHasPedido() as $produto){
                        $total += $produto->getValor();
                    }
                ?>
                <td>
                    #<?=$pedido->getSenha(); ?>
                </td>
                <td>
                    <?=$pedido->getCliente()->getNome() ?>
                </td>
                <td>
                    <?= count($pedido->getProdutoHasPedido()); ?>
                </td>
                <td>
                    R$ <?= str_pad( $total, 4, '0', STR_PAD_RIGHT ); ?>
                </td>
                <td>
                    Concluido
                </td>
                <td class="span2">
                    <a href="#" class="btn btn-inverse span2" data-toggle="modal" data-target="#<?= $pedido->getId(); ?>"><i class="icon-eye-open"></i>Ver</a>
                </td>
            </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </table>
</div>
<?php if($modal): ?>
        <?php foreach($this->pedidos as $pedido): ?>
            <div class="modal hide fade" id="<?= $pedido->getId(); ?>">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4><?= $pedido->getCliente()->getNome(); ?></h4>
                </div>
                <div class="modal-body">
                    <?php foreach($pedido->getProdutoHasPedido() as $produto):  $ant = '';?>
                            <ul class="nav">
                                <?php foreach($produto->getProdutoItens() as $item): ?>
                                    <?php $next = $item->getItens()->getProduto()->getNome(); ?>
                                    <?php if(!($ant == $next)): ?>
                                        <hr />
                                        <?= "<h3>".$item->getItens()->getProduto()->getNome()."</h3>"; ?>
                                        <?php $ant = $next; ?>
                                    <?php endif; ?>
                                    <li>
                                        <?= $item->getItens()->getDescricao() ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                    <?php endforeach; ?>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn" data-dismiss="modal">Fechar [x]</a>
                </div>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>